contacts/urls.py
from django.conf.urls import url

from . import views

app_name = 'contacts'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<person_id>[0-9]+)/$', views.person_detail, name= 'person_detail'),
    url(r'^(?P<person_id>[0-9]+)/update/$', views.update, name= 'update')
    ]

easycontacts/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^contacts/', include('contacts.urls')),
    url(r'^admin/', admin.site.urls),
]

contacts/models.py
from django.db import models

# Create your models here.

class Person(models.Model):
    name = models.CharField(max_length=100)
    employer = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name
        
class Contact(models.Model):
    EMAIL = 'em'
    PHONE = 'ph'
    IN_PERSON = 'ip'
    OTHER = 'ot'
    CONTACT_TYPE_CHOICES = (
        (EMAIL, 'email'),
        (PHONE, 'phone'),
        (IN_PERSON, 'in person'),
        (OTHER, 'other'),
    )
    
    date = models.DateTimeField('date contacted')
    contact_type = models.CharField(
        max_length =2,
        choices=CONTACT_TYPE_CHOICES,
        default=EMAIL)
        
    def __str__(self):
        return self.date
    

contacts/forms.py
from django import forms

class PersonForm(forms.Form):
    def __init__(self, *args, **kwargs):
        person = args[0].pop('person')
        initial = kwargs.get('initial',{})
        initial['employer']= person.employer
        initial['email'] = person.email
        kwargs['initial'] = initial
        super().__init__(*args, **kwargs)

        '''

        self.fields['employer'].initial = person.employer
        self.fields['email'].initial = person.email
        '''
        
        
    employer = forms.CharField(label='Employer',max_length=100)
    email = forms.CharField(label='Email', max_length=100)

contacts/views.py
from django.http import HttpResponse
from django.shortcuts import render,get_object_or_404
from django.contrib.auth.decorators import login_required

from .models import Person
from .forms import PersonForm

@login_required
def index(request):
    person_list = Person.objects.order_by('name')
    context = {'person_list':person_list}
    return render(request, 'contacts/index.html', context)
   
@login_required
def person_detail(request, person_id):
    person = get_object_or_404(Person, pk=person_id)
    form = PersonForm({'person':person})
    return render(request, 'contacts/detail.html', {'person':person,'form':form})
 
@login_required
def update(request, person_id):
    person = get_object_or_404(Person, pk=person_id)
    person.email = request.POST['email']
    person.employer = request.POST['employer']
    person.save()
    return render(request, 'contacts/detail.html', {'person': person})

contacts/templates/contacts/base.html
<html>
    <head>
        <title>Contacts</title>
        {% include 'material/includes/material_css.html' %}
        <script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>
        {% include 'material/includes/material_js.html' %}
    </head>
    <body>
        {% block content %}
        {% endblock %}
    </body>
</html>

contacts/templates/contacts/detail.html
{% extends 'contacts/base.html' %}

{% block content %}
<h1>{{ person.name }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
{% load material_form %}

<form action="{% url 'contacts:update' person.id%}" method="post">
    {% csrf_token %}
    {% form form=form %}{% endform %}
    <input type="submit" value="Update" />
</form>

{% endblock %}

contacts/templates/contacts/index.html
{% if person_list %}
   <ul>
       {% for person in person_list %}
        <li><a href="{% url 'contacts:person_detail' person.id %}">{{person.name}}</a></li>
        {% endfor %}
   </ul>
  {% endif %}